image: golang:alpine

cache:
  paths:
    - /apt-cache
    - /go/src/github.com
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - test
  - build

before_script:
  - apk update && apk add curl golang && rm -rf /var/cache/apk/*
  - export GOROOT="/usr/lib/go"
  - export GOPATH="/gopath"
  - export GOBIN="/gopath/bin"
  - export PATH="$PATH:$GOROOT/bin:$GOPATH/bin"
  - sudo apt update && sudo apt install golang
  - go get -u github.com/golang/dep/cmd/dep 
  - export GOPATH=$(dirname $CI_PROJECT_DIR)/go
  - mkdir -p $GOPATH/src
  - cd $GOPATH/src
  - ln -s $CI_PROJECT_DIR
  - cd $CI_PROJECT_NAME
  - dep ensure -update
#  - mkdir -p /go/src/gitlab.com/tsi-automation /go/src/_/builds
#  - cp -r $CI_PROJECT_DIR /go/src/gitlab.com/tsi-automation/inspec_exporter
#  - ln -s /go/src/gitlab.com/tsi-automation /go/src/_/builds/tsi-automation
#  - make dep

#unit_tests:
#  stage: test
#  script:
#    - make test


style:
  stage: test
  script:
    - make style
    
format:
  stage: test
  script:
    - make format
    
vet:
  stage: test
  script:
    - make vet

build:
  stage: build
  script:
    - make build

docker:
  stage: build
  script:
    - make docker
